version: "3"
services:
  renovate-poc:
    build:
      context: .
    network_mode: "host"
    container_name: renovate-poc
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

  localstack:
    image: localstack/localstack:0.14.0

networks:
  hmpps:
